# action.yaml
name: 'PyInstaller Windows'
description: 'Customisable GitHub Action to package your python code with PyInstaller for Windows'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  path:
    description: 'Directory containing source code & .spec file (optional requirements.txt).'
    required: True
    default: src
  pypi_url:
    description: 'Specify a custom URL for PYPI'
    required: False
    default: https://pypi.python.org/
  pypi_index_url:
    description: 'Specify a custom URL for PYPI Index'
    required: False
    default: https://pypi.python.org/simple
outputs:
  output:
    description: 'The output of PyInstaller'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}